mod block;
mod code_reference;
mod data_block;
mod data_block_kind_azuread;
mod data_block_kind_azuredevops;
mod data_block_kind_azurerm;
mod data_block_kind_other;
mod data_block_reference;
mod data_block_resource_kind;
mod import_block;
mod plan;
mod provider_block;
mod provider_kind;
mod provider_reference;
mod resource_block;
mod resource_block_kind_azuread;
mod resource_block_kind_azuredevops;
mod resource_block_kind_azurerm;
mod resource_block_kind_other;
mod resource_block_reference;
mod resource_block_resource_kind;
mod sanitize;
mod strings;
mod terraform_block;
mod terraform_registry_provider;
mod tf_work_dir;
mod users_lookup_body;
mod version;
pub mod prelude {
    pub use crate::block::*;
    pub use crate::code_reference::*;
    pub use crate::data_block::*;
    pub use crate::data_block_kind_azuread::*;
    pub use crate::data_block_kind_azuredevops::*;
    pub use crate::data_block_kind_azurerm::*;
    pub use crate::data_block_kind_other::*;
    pub use crate::data_block_reference::*;
    pub use crate::data_block_resource_kind::*;
    pub use crate::import_block::*;
    pub use crate::plan::*;
    pub use crate::provider_block::*;
    pub use crate::provider_kind::*;
    pub use crate::provider_reference::*;
    pub use crate::resource_block::*;
    pub use crate::resource_block_kind_azuread::*;
    pub use crate::resource_block_kind_azuredevops::*;
    pub use crate::resource_block_kind_azurerm::*;
    pub use crate::resource_block_kind_other::*;
    pub use crate::resource_block_reference::*;
    pub use crate::resource_block_resource_kind::*;
    pub use crate::sanitize::*;
    pub use crate::strings::*;
    pub use crate::terraform_block::*;
    pub use crate::terraform_registry_provider::*;
    pub use crate::tf_work_dir::*;
    pub use crate::users_lookup_body::*;
    pub use crate::version::*;
    pub use hcl::*;
}
