[package]
name = "azure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
fzf = { workspace = true }
tempfile = { workspace = true }
command = { workspace = true }
tofu_types = { workspace = true }
azure_types = { workspace = true }
tracing = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
indoc = { workspace = true }
pathing_types = { workspace = true }
humantime = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }