allowed-duplicate-crates = [
    "bitflags",
    "compact_str",
    "core-foundation",
    "core-graphics-types",
    "foldhash",
    "foreign-types",
    "foreign-types-shared",
    "getrandom",
    "hashbrown",
    "itertools",
    "linux-raw-sys",
    "objc2",
    "objc2-app-kit",
    "objc2-foundation",
    "quick-xml",
    "rand",
    "rand_chacha",
    "rand_core",
    "redox_syscall",
    "rustc-hash",
    "rustix",
    "strum",
    "strum_macros",
    "thiserror",
    "thiserror-impl",
    "unicode-width",
    "wasi",
    "windows",
    "windows-collections",
    "windows-core",
    "windows-future",
    "windows-implement",
    "windows-interface",
    "windows-link",
    "windows-numerics",
    "windows-result",
    "windows-strings",
    "windows-sys",
    "windows-targets",
    "windows-threading",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
