#![feature(impl_trait_in_assoc_type, duration_constructors, async_fn_track_caller)]
mod access_token;
mod accounts;
mod auth;
mod batch_api;
mod compute_sku_prices;
mod compute_skus;
mod conditional_access_named_locations;
mod conditional_access_policies;
mod container_registry;
mod cost_management;
mod create_role_assignment;
mod eligible_child_resources;
mod evaluate_policy_assignment_compliance;
mod governance_role_assignments;
mod group_members;
mod group_owners;
mod groups;
mod import;
mod key_vault_secrets;
mod key_vaults;
mod locations;
mod management_groups;
mod metrics;
mod microsoft_graph;
mod microsoft_graph_batch;
mod name_lookup_helper;
mod oauth2_permission_grants;
mod oauth2_permission_scopes;
mod pick_oauth2_permission_grants;
mod pim_azurerm_activate;
mod pim_entra_activate;
mod pim_entra_role_assignments;
mod pim_entra_role_definitions;
mod pim_entra_role_settings;
mod policy_assignments;
mod policy_definitions;
mod policy_set_definitions;
mod principals;
mod remediate_policy_assignment;
mod remove_oauth2_permission_grant;
mod resource_graph;
mod resource_group_choices;
mod resource_groups;
mod resources;
mod role_assignment_choices;
mod role_assignments;
mod role_definitions;
mod role_definitions_and_assignments;
mod role_eligibility_schedules;
mod role_management_policy_assignments;
mod route_table;
mod security_group_choices;
mod security_groups;
mod service_groups;
mod service_principals;
mod storage_account;
mod subscriptions;
mod tags;
mod tenant_licenses;
mod tenants;
mod unified_role_assignments;
mod unified_role_definition;
mod unified_role_definitions;
mod unified_role_definitions_and_assignments;
mod users;
mod virtual_machine_prices;
mod virtual_machine_sizes;
mod virtual_machine_skus;
mod virtual_network;
pub mod prelude {
    pub use crate::access_token::*;
    pub use crate::accounts::*;
    pub use crate::auth::*;
    pub use crate::batch_api::*;
    pub use crate::compute_sku_prices::*;
    pub use crate::compute_skus::*;
    pub use crate::conditional_access_named_locations::*;
    pub use crate::conditional_access_policies::*;
    pub use crate::container_registry::*;
    pub use crate::cost_management::*;
    pub use crate::create_role_assignment::*;
    pub use crate::eligible_child_resources::*;
    pub use crate::evaluate_policy_assignment_compliance::*;
    pub use crate::governance_role_assignments::*;
    pub use crate::group_members::*;
    pub use crate::group_owners::*;
    pub use crate::groups::*;
    pub use crate::import::*;
    pub use crate::key_vault_secrets::*;
    pub use crate::key_vaults::*;
    pub use crate::locations::*;
    pub use crate::management_groups::*;
    pub use crate::metrics::*;
    pub use crate::microsoft_graph::*;
    pub use crate::microsoft_graph_batch::*;
    pub use crate::name_lookup_helper::*;
    pub use crate::oauth2_permission_grants::*;
    pub use crate::oauth2_permission_scopes::*;
    pub use crate::pick_oauth2_permission_grants::*;
    pub use crate::pim_azurerm_activate::*;
    pub use crate::pim_entra_activate::*;
    pub use crate::pim_entra_role_assignments::*;
    pub use crate::pim_entra_role_definitions::*;
    pub use crate::pim_entra_role_settings::*;
    pub use crate::policy_assignments::*;
    pub use crate::policy_definitions::*;
    pub use crate::policy_set_definitions::*;
    pub use crate::principals::*;
    pub use crate::remediate_policy_assignment::*;
    pub use crate::remove_oauth2_permission_grant::*;
    pub use crate::resource_graph::*;
    pub use crate::resource_group_choices::*;
    pub use crate::resource_groups::*;
    pub use crate::resources::*;
    pub use crate::role_assignment_choices::*;
    pub use crate::role_assignments::*;
    pub use crate::role_definitions::*;
    pub use crate::role_definitions_and_assignments::*;
    pub use crate::role_eligibility_schedules::*;
    pub use crate::role_management_policy_assignments::*;
    pub use crate::route_table::*;
    pub use crate::security_group_choices::*;
    pub use crate::security_groups::*;
    pub use crate::service_groups::*;
    pub use crate::service_principals::*;
    pub use crate::storage_account::*;
    pub use crate::subscriptions::*;
    pub use crate::tags::*;
    pub use crate::tenant_licenses::*;
    pub use crate::tenants::*;
    pub use crate::unified_role_assignments::*;
    pub use crate::unified_role_definition::*;
    pub use crate::unified_role_definitions::*;
    pub use crate::unified_role_definitions_and_assignments::*;
    pub use crate::users::*;
    pub use crate::virtual_machine_prices::*;
    pub use crate::virtual_machine_sizes::*;
    pub use crate::virtual_machine_skus::*;
    pub use crate::virtual_network::*;
    pub use cloud_terrastodon_azure_types::prelude::*;
}
