[package]
name = "command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true } 
anyhow = { workspace = true } 
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
async-recursion = { workspace = true }
tracing = { workspace = true }
