[package]
name = "cloud_terrastodon_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
crossterm = { workspace = true }
futures = { workspace = true }