[package]
name = "cloud_terrasotodon_core_tofu_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud_terrasotodon_core_command = { workspace = true }
cloud_terrasotodon_core_fzf = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
itertools = { workspace = true }
indoc = { workspace = true }
hcl-rs = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
# unidecode = { workspace = true }
hcl-primitives = { workspace = true }