mod azure_devops_account_id;
mod azure_devops_agent_package;
mod azure_devops_agent_pool;
mod azure_devops_agent_pool_argument;
mod azure_devops_agent_pool_entitlement;
mod azure_devops_agent_pool_entitlement_id;
mod azure_devops_agent_pool_id;
mod azure_devops_agent_pool_name;
mod azure_devops_descriptor;
mod azure_devops_entra_user_descriptor;
mod azure_devops_group;
mod azure_devops_group_license_entitlement;
mod azure_devops_group_member;
mod azure_devops_json_patch;
mod azure_devops_json_patch_operation;
mod azure_devops_license_rule;
mod azure_devops_license_type;
mod azure_devops_organization_name;
mod azure_devops_organization_url;
mod azure_devops_project;
mod azure_devops_project_argument;
mod azure_devops_project_id;
mod azure_devops_project_name;
mod azure_devops_repo_id;
mod azure_devops_repos;
mod azure_devops_service_endpoint;
mod azure_devops_service_endpoint_authorization;
mod azure_devops_service_endpoint_created_by;
mod azure_devops_service_endpoint_data;
mod azure_devops_service_endpoint_data_azurerm;
mod azure_devops_service_endpoint_id;
mod azure_devops_service_endpoint_kind;
mod azure_devops_service_endpoint_name;
mod azure_devops_service_endpoint_operation_status;
mod azure_devops_service_endpoint_owner;
mod azure_devops_service_endpoint_project_reference;
mod azure_devops_suite_test_case;
mod azure_devops_team;
mod azure_devops_team_id;
mod azure_devops_team_member;
mod azure_devops_test_case_work_item_reference;
mod azure_devops_test_plan;
mod azure_devops_test_suite;
mod azure_devops_user_argument;
mod azure_devops_user_id;
mod azure_devops_user_license_entitlement;
mod azure_devops_work_item;
mod azure_devops_work_item_expand;
mod azure_devops_work_item_field_definition;
mod azure_devops_work_item_field_name;
mod azure_devops_work_item_fields;
mod azure_devops_work_item_id;
mod azure_devops_work_item_identity;
mod azure_devops_work_item_identity_avatar;
mod azure_devops_work_item_identity_links;
mod azure_devops_work_item_patch_fields;
mod azure_devops_work_item_project_url;
mod azure_devops_work_item_query;
mod azure_devops_work_item_query_flattened_hierarchy_entry;
mod azure_devops_work_item_query_id;
mod azure_devops_work_item_query_path;
mod azure_devops_work_item_relation;
mod azure_devops_work_item_relation_attributes;
mod azure_devops_work_item_relation_input;
mod azure_devops_work_item_relation_input_attributes;
mod azure_devops_work_item_relation_type;
mod azure_devops_work_item_relation_type_name;
mod azure_devops_work_item_relation_url;
mod azure_devops_work_item_type;
mod azure_devops_work_item_type_definition;
mod azure_devops_work_item_type_field;
mod azure_devops_work_item_url;
mod query_result_type;
mod query_type;
mod work_item_field_reference;
mod work_item_link;
mod work_item_query_result;
mod work_item_query_sort_column;
mod work_item_reference;

pub use crate::azure_devops_account_id::*;
pub use crate::azure_devops_agent_package::*;
pub use crate::azure_devops_agent_pool::*;
pub use crate::azure_devops_agent_pool_argument::*;
pub use crate::azure_devops_agent_pool_entitlement::*;
pub use crate::azure_devops_agent_pool_entitlement_id::*;
pub use crate::azure_devops_agent_pool_id::*;
pub use crate::azure_devops_agent_pool_name::*;
pub use crate::azure_devops_descriptor::*;
pub use crate::azure_devops_entra_user_descriptor::*;
pub use crate::azure_devops_group::*;
pub use crate::azure_devops_group_license_entitlement::*;
pub use crate::azure_devops_group_member::*;
pub use crate::azure_devops_json_patch::*;
pub use crate::azure_devops_json_patch_operation::*;
pub use crate::azure_devops_license_rule::*;
pub use crate::azure_devops_license_type::*;
pub use crate::azure_devops_organization_name::*;
pub use crate::azure_devops_organization_url::*;
pub use crate::azure_devops_project::*;
pub use crate::azure_devops_project_argument::*;
pub use crate::azure_devops_project_id::*;
pub use crate::azure_devops_project_name::*;
pub use crate::azure_devops_repo_id::*;
pub use crate::azure_devops_repos::*;
pub use crate::azure_devops_service_endpoint::*;
pub use crate::azure_devops_service_endpoint_authorization::*;
pub use crate::azure_devops_service_endpoint_created_by::*;
pub use crate::azure_devops_service_endpoint_data::*;
pub use crate::azure_devops_service_endpoint_data_azurerm::*;
pub use crate::azure_devops_service_endpoint_id::*;
pub use crate::azure_devops_service_endpoint_kind::*;
pub use crate::azure_devops_service_endpoint_name::*;
pub use crate::azure_devops_service_endpoint_operation_status::*;
pub use crate::azure_devops_service_endpoint_owner::*;
pub use crate::azure_devops_service_endpoint_project_reference::*;
pub use crate::azure_devops_suite_test_case::*;
pub use crate::azure_devops_team::*;
pub use crate::azure_devops_team_id::*;
pub use crate::azure_devops_team_member::*;
pub use crate::azure_devops_test_case_work_item_reference::*;
pub use crate::azure_devops_test_plan::*;
pub use crate::azure_devops_test_suite::*;
pub use crate::azure_devops_user_argument::*;
pub use crate::azure_devops_user_id::*;
pub use crate::azure_devops_user_license_entitlement::*;
pub use crate::azure_devops_work_item::*;
pub use crate::azure_devops_work_item_expand::*;
pub use crate::azure_devops_work_item_field_definition::*;
pub use crate::azure_devops_work_item_field_name::*;
pub use crate::azure_devops_work_item_fields::*;
pub use crate::azure_devops_work_item_id::*;
pub use crate::azure_devops_work_item_identity::*;
pub use crate::azure_devops_work_item_identity_avatar::*;
pub use crate::azure_devops_work_item_identity_links::*;
pub use crate::azure_devops_work_item_patch_fields::*;
pub use crate::azure_devops_work_item_project_url::*;
pub use crate::azure_devops_work_item_query::*;
pub use crate::azure_devops_work_item_query_flattened_hierarchy_entry::*;
pub use crate::azure_devops_work_item_query_id::*;
pub use crate::azure_devops_work_item_query_path::*;
pub use crate::azure_devops_work_item_relation::*;
pub use crate::azure_devops_work_item_relation_attributes::*;
pub use crate::azure_devops_work_item_relation_input::*;
pub use crate::azure_devops_work_item_relation_input_attributes::*;
pub use crate::azure_devops_work_item_relation_type::*;
pub use crate::azure_devops_work_item_relation_type_name::*;
pub use crate::azure_devops_work_item_relation_url::*;
pub use crate::azure_devops_work_item_type::*;
pub use crate::azure_devops_work_item_type_definition::*;
pub use crate::azure_devops_work_item_type_field::*;
pub use crate::azure_devops_work_item_url::*;
pub use crate::query_result_type::*;
pub use crate::query_type::*;
pub use crate::work_item_field_reference::*;
pub use crate::work_item_link::*;
pub use crate::work_item_query_result::*;
pub use crate::work_item_query_sort_column::*;
pub use crate::work_item_reference::*;
