mod azure_devops_descriptor;
mod azure_devops_account_id;
mod azure_devops_entra_user_descriptor;
mod azure_devops_group;
mod azure_devops_group_member;
mod azure_devops_organization_name;
mod azure_devops_organization_url;
mod azure_devops_project;
mod azure_devops_project_argument;
mod azure_devops_project_id;
mod azure_devops_project_name;
mod azure_devops_repos;
mod azure_devops_service_endpoint;
mod azure_devops_service_endpoint_data;
mod azure_devops_service_endpoint_data_azurerm;
mod azure_devops_service_endpoint_id;
mod azure_devops_service_endpoint_kind;
mod azure_devops_service_endpoint_name;
mod azure_devops_team;
mod azure_devops_team_member;
mod azure_devops_user_license_entitlement;
mod azure_devops_user_id;
mod azure_devops_work_item_query;
mod azure_devops_work_items;
mod azure_devops_service_endpoint_authorization;
mod azure_devops_service_endpoint_created_by;
mod azure_devops_service_endpoint_operation_status;
mod azure_devops_service_endpoint_owner;
mod azure_devops_service_endpoint_project_reference;

pub mod prelude {
    pub use crate::azure_devops_descriptor::*;
    pub use crate::azure_devops_account_id::*;
    pub use crate::azure_devops_service_endpoint_project_reference::*;
    pub use crate::azure_devops_service_endpoint_owner::*;
    pub use crate::azure_devops_service_endpoint_operation_status::*;
    pub use crate::azure_devops_service_endpoint_created_by::*;
    pub use crate::azure_devops_service_endpoint_authorization::*;
    pub use crate::azure_devops_entra_user_descriptor::*;
    pub use crate::azure_devops_group::*;
    pub use crate::azure_devops_group_member::*;
    pub use crate::azure_devops_organization_name::*;
    pub use crate::azure_devops_organization_url::*;
    pub use crate::azure_devops_project::*;
    pub use crate::azure_devops_project_argument::*;
    pub use crate::azure_devops_project_id::*;
    pub use crate::azure_devops_project_name::*;
    pub use crate::azure_devops_repos::*;
    pub use crate::azure_devops_service_endpoint::*;
    pub use crate::azure_devops_service_endpoint_data::*;
    pub use crate::azure_devops_service_endpoint_data_azurerm::*;
    pub use crate::azure_devops_service_endpoint_id::*;
    pub use crate::azure_devops_service_endpoint_kind::*;
    pub use crate::azure_devops_service_endpoint_name::*;
    pub use crate::azure_devops_team::*;
    pub use crate::azure_devops_team_member::*;
    pub use crate::azure_devops_user_license_entitlement::*;
    pub use crate::azure_devops_user_id::*;
    pub use crate::azure_devops_work_item_query::*;
    pub use crate::azure_devops_work_items::*;
}
