[package]
name = "cloud_terrastodon_pathing"
description = "Well-known paths for the Cloud Terrastodon project"
version = "0.28.0" # CT_VERSION
readme.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
directories-next = { workspace = true }
async-trait.workspace = true

















