[package]
name = "cloud_terrastodon_pathing"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
directories-next = { workspace = true }
async-trait.workspace = true
