#![allow(
    clippy::infallible_try_from,
    reason = "Facet proxy and string wrapper conversions intentionally keep TryFrom-compatible patterns across the crate"
)]
mod access_token;
mod accounts;
mod address_prefix;
mod address_prefixes;
mod all_or;
mod arbitrary_json;
mod azure_app_service_resource;
mod azure_app_service_resource_id;
mod azure_app_service_resource_name;
mod azure_application_gateway_resource;
mod azure_application_gateway_resource_backend_health;
mod azure_application_gateway_resource_id;
mod azure_application_gateway_resource_name;
mod azure_cognitive_services_account_deployment;
mod azure_cognitive_services_account_deployment_id;
mod azure_cognitive_services_account_deployment_name;
mod azure_cognitive_services_account_resource;
mod azure_cognitive_services_account_resource_id;
mod azure_cognitive_services_account_resource_name;
mod azure_container_instance_resource;
mod azure_container_instance_resource_id;
mod azure_container_instance_resource_name;
mod azure_network_interface_resource;
mod azure_network_interface_resource_id;
mod azure_network_interface_resource_name;
mod azure_principal_argument;
mod azure_private_endpoint_resource;
mod azure_private_endpoint_resource_id;
mod azure_private_endpoint_resource_name;
mod azure_public_ip_resource;
mod azure_public_ip_resource_id;
mod azure_public_ip_resource_name;
mod azure_role_definition_argument;
mod azure_tenant_argument;
mod azure_tenant_cloud_terrastodon_alias;
mod compute_publisher_id;
mod compute_publisher_name;
mod compute_publisher_vm_image_offer_id;
mod compute_publisher_vm_image_offer_name;
mod compute_publisher_vm_image_offer_sku_id;
mod compute_publisher_vm_image_offer_sku_name;
mod compute_publisher_vm_image_offer_sku_properties;
mod compute_publisher_vm_image_offer_sku_version;
mod compute_publisher_vm_image_offer_sku_version_id;
mod compute_publisher_vm_image_offer_sku_version_name;
mod compute_publisher_vm_image_offer_sku_version_properties;
mod compute_sku;
mod compute_sku_name;
mod conditional_access_named_location;
mod conditional_access_named_location_id;
mod conditional_access_policy;
mod conditional_access_policy_id;
mod container_registry;
mod container_registry_id;
mod container_registry_name;
mod container_registry_repository_name;
mod container_registry_repository_tag;
mod cost_management;
mod eligible_child_resources;
mod entra_application_client_id;
mod entra_application_object_id;
mod entra_application_registration;
mod entra_directory_object;
mod entra_directory_object_type;
mod entra_oauth_scope;
mod entra_oauth_scope_claim;
mod entra_service_principal;
mod entra_service_principal_application_permissions;
mod entra_service_principal_application_resource_specific_permission;
mod entra_service_principal_application_role;
mod entra_service_principal_application_role_id;
mod entra_service_principal_object_id;
mod entra_user;
#[cfg(test)]
mod facet_json_equivalence;
mod facet_proxies;
mod governance_role_assignment;
mod governance_role_definition;
mod governance_role_definition_name;
mod group;
mod group_id;
mod iso8601_duration;
mod key_vault;
mod key_vault_access;
mod key_vault_access_policies;
mod key_vault_access_policy_all_privilege;
mod key_vault_access_policy_certificate_privileges;
mod key_vault_access_policy_key_privilege;
mod key_vault_access_policy_secret_privilege;
mod key_vault_id;
mod key_vault_name;
mod key_vault_properties;
mod key_vault_secret;
mod key_vault_secret_id;
mod key_vault_secret_name;
mod key_vault_secret_version_id;
mod location;
mod management_group_ancestors_chain;
mod management_groups;
mod metrics;
mod microsoft_graph_directory_object;
mod microsoft_graph_entity;
mod microsoft_graph_entity_id;
mod microsoft_graph_organization;
mod microsoft_graph_scope;
mod naming;
mod oauth2_permission_grants;
mod oauth2_permission_scopes;
mod openid_connect_scope;
mod pim_azurerm_role_assignment_schedule_requests;
mod pim_entra_role_assignment_requests;
mod pim_entra_role_definitions;
mod pim_entra_role_settings;
mod policy_assignment;
mod policy_assignment_id;
mod policy_assignment_id_variants;
mod policy_assignment_name;
mod policy_definition;
mod policy_definition_id;
mod policy_definition_id_reference;
mod policy_definition_id_variants;
mod policy_definition_name;
mod policy_definition_policy_rule;
mod policy_parameters_definition;
mod policy_parameters_supplied;
mod policy_set_definition;
mod policy_set_definition_id;
mod policy_set_definition_id_variants;
mod policy_set_definition_name;
mod price;
mod principal;
mod principal_collection;
mod principal_id;
mod principal_ref;
mod query_response;
mod resource_group;
mod resource_group_id;
mod resource_group_map;
mod resource_group_name;
mod resource_tags;
mod resources;
mod role_assignment;
mod role_assignment_id;
mod role_assignment_id_variants;
mod role_assignment_name;
mod role_definition_id;
mod role_definition_id_variants;
mod role_definition_name;
mod role_definitions;
mod role_definitions_and_assignments;
mod role_eligibility_schedule_id;
mod role_eligibility_schedule_id_variants;
mod role_eligibility_schedule_name;
mod role_eligibility_schedules;
mod role_management_policy_assignment_id;
mod role_management_policy_assignment_id_variants;
mod role_management_policy_assignment_name;
mod role_management_policy_assignments;
mod role_management_policy_id;
mod role_management_policy_id_variants;
mod role_operations;
mod role_permission;
mod role_permission_action;
mod role_permission_action_set;
mod route_table;
mod route_table_id;
mod route_table_name;
mod route_table_properties;
mod scope_itertools;
mod scopes;
mod service_group;
mod service_group_id;
mod service_group_name;
mod slug;
mod storage_account;
mod storage_account_blob_container_name;
mod storage_account_id;
mod storage_account_name;
mod subnet;
mod subnet_id;
mod subnet_name;
mod subnet_properties;
mod subscription;
mod subscription_id;
mod subscription_name;
mod tenant_id;
mod tenant_license;
mod test_resource;
mod unified_role_assignment;
mod unified_role_assignment_id;
mod unified_role_definition;
mod unified_role_definition_collection;
mod unified_role_definition_id;
mod unified_role_definitions_and_assignments;
mod user_id;
mod uuid_macros;
mod virtual_machine;
mod virtual_machine_id;
mod virtual_machine_name;
mod virtual_machine_properties;
mod virtual_machine_size;
mod virtual_network;
mod virtual_network_id;
mod virtual_network_name;
mod virtual_network_peering_id;
mod virtual_network_peering_name;
mod virtual_network_properties;

pub use crate::access_token::*;
pub use crate::accounts::*;
pub use crate::address_prefix::*;
pub use crate::address_prefixes::*;
pub use crate::all_or::*;
pub use crate::arbitrary_json::*;
pub use crate::azure_app_service_resource::*;
pub use crate::azure_app_service_resource_id::*;
pub use crate::azure_app_service_resource_name::*;
pub use crate::azure_application_gateway_resource::*;
pub use crate::azure_application_gateway_resource_backend_health::*;
pub use crate::azure_application_gateway_resource_id::*;
pub use crate::azure_application_gateway_resource_name::*;
pub use crate::azure_cognitive_services_account_deployment::*;
pub use crate::azure_cognitive_services_account_deployment_id::*;
pub use crate::azure_cognitive_services_account_deployment_name::*;
pub use crate::azure_cognitive_services_account_resource::*;
pub use crate::azure_cognitive_services_account_resource_id::*;
pub use crate::azure_cognitive_services_account_resource_name::*;
pub use crate::azure_container_instance_resource::*;
pub use crate::azure_container_instance_resource_id::*;
pub use crate::azure_container_instance_resource_name::*;
pub use crate::azure_network_interface_resource::*;
pub use crate::azure_network_interface_resource_id::*;
pub use crate::azure_network_interface_resource_name::*;
pub use crate::azure_principal_argument::*;
pub use crate::azure_private_endpoint_resource::*;
pub use crate::azure_private_endpoint_resource_id::*;
pub use crate::azure_private_endpoint_resource_name::*;
pub use crate::azure_public_ip_resource::*;
pub use crate::azure_public_ip_resource_id::*;
pub use crate::azure_public_ip_resource_name::*;
pub use crate::azure_role_definition_argument::*;
pub use crate::azure_tenant_argument::*;
pub use crate::azure_tenant_cloud_terrastodon_alias::*;
pub use crate::compute_publisher_id::*;
pub use crate::compute_publisher_name::*;
pub use crate::compute_publisher_vm_image_offer_id::*;
pub use crate::compute_publisher_vm_image_offer_name::*;
pub use crate::compute_publisher_vm_image_offer_sku_id::*;
pub use crate::compute_publisher_vm_image_offer_sku_name::*;
pub use crate::compute_publisher_vm_image_offer_sku_properties::*;
pub use crate::compute_publisher_vm_image_offer_sku_version::*;
pub use crate::compute_publisher_vm_image_offer_sku_version_id::*;
pub use crate::compute_publisher_vm_image_offer_sku_version_name::*;
pub use crate::compute_publisher_vm_image_offer_sku_version_properties::*;
pub use crate::compute_sku::*;
pub use crate::compute_sku_name::*;
pub use crate::conditional_access_named_location::*;
pub use crate::conditional_access_named_location_id::*;
pub use crate::conditional_access_policy::*;
pub use crate::conditional_access_policy_id::*;
pub use crate::container_registry::*;
pub use crate::container_registry_id::*;
pub use crate::container_registry_name::*;
pub use crate::container_registry_repository_name::*;
pub use crate::container_registry_repository_tag::*;
pub use crate::cost_management::*;
pub use crate::eligible_child_resources::*;
pub use crate::entra_application_client_id::*;
pub use crate::entra_application_registration::*;
pub use crate::entra_directory_object::*;
pub use crate::entra_directory_object_type::*;
pub use crate::entra_oauth_scope::*;
pub use crate::entra_oauth_scope_claim::*;
pub use crate::entra_service_principal::*;
pub use crate::entra_service_principal_application_permissions::*;
pub use crate::entra_service_principal_application_resource_specific_permission::*;
pub use crate::entra_service_principal_application_role::*;
pub use crate::entra_service_principal_application_role_id::*;
pub use crate::entra_service_principal_object_id::*;
pub use crate::entra_user::*;
pub use crate::facet_proxies::*;
pub use crate::governance_role_assignment::*;
pub use crate::governance_role_definition::*;
pub use crate::governance_role_definition_name::*;
pub use crate::group::*;
pub use crate::group_id::*;
pub use crate::iso8601_duration::*;
pub use crate::key_vault::*;
pub use crate::key_vault_access_policies::*;
pub use crate::key_vault_access_policy_all_privilege::*;
pub use crate::key_vault_access_policy_certificate_privileges::*;
pub use crate::key_vault_access_policy_key_privilege::*;
pub use crate::key_vault_access_policy_secret_privilege::*;
pub use crate::key_vault_id::*;
pub use crate::key_vault_name::*;
pub use crate::key_vault_properties::*;
pub use crate::key_vault_secret::*;
pub use crate::key_vault_secret_id::*;
pub use crate::key_vault_secret_name::*;
pub use crate::key_vault_secret_version_id::*;
pub use crate::location::*;
pub use crate::management_group_ancestors_chain::*;
pub use crate::management_groups::*;
pub use crate::metrics::*;
pub use crate::microsoft_graph_directory_object::*;
pub use crate::microsoft_graph_entity::*;
pub use crate::microsoft_graph_entity_id::*;
pub use crate::microsoft_graph_organization::*;
pub use crate::microsoft_graph_scope::*;
pub use crate::naming::*;
pub use crate::oauth2_permission_grants::*;
pub use crate::oauth2_permission_scopes::*;
pub use crate::openid_connect_scope::*;
pub use crate::pim_azurerm_role_assignment_schedule_requests::*;
pub use crate::pim_entra_role_assignment_requests::*;
pub use crate::pim_entra_role_definitions::*;
pub use crate::pim_entra_role_settings::*;
pub use crate::policy_assignment::*;
pub use crate::policy_assignment_id::*;
pub use crate::policy_assignment_id_variants::*;
pub use crate::policy_assignment_name::*;
pub use crate::policy_definition::*;
pub use crate::policy_definition_id::*;
pub use crate::policy_definition_id_reference::*;
pub use crate::policy_definition_id_variants::*;
pub use crate::policy_definition_name::*;
pub use crate::policy_definition_policy_rule::*;
pub use crate::policy_parameters_definition::*;
pub use crate::policy_parameters_supplied::*;
pub use crate::policy_set_definition::*;
pub use crate::policy_set_definition_id::*;
pub use crate::policy_set_definition_id_variants::*;
pub use crate::policy_set_definition_name::*;
pub use crate::price::*;
pub use crate::principal::*;
pub use crate::principal_collection::*;
pub use crate::principal_id::*;
pub use crate::principal_ref::*;
pub use crate::query_response::*;
pub use crate::resource_group::*;
pub use crate::resource_group_id::*;
pub use crate::resource_group_map::*;
pub use crate::resource_group_name::*;
pub use crate::resource_tags::*;
pub use crate::resources::*;
pub use crate::role_assignment::*;
pub use crate::role_assignment_id::*;
pub use crate::role_assignment_id_variants::*;
pub use crate::role_assignment_name::*;
pub use crate::role_definition_id::*;
pub use crate::role_definition_id_variants::*;
pub use crate::role_definition_name::*;
pub use crate::role_definitions::*;
pub use crate::role_definitions_and_assignments::*;
pub use crate::role_eligibility_schedule_id::*;
pub use crate::role_eligibility_schedule_id_variants::*;
pub use crate::role_eligibility_schedule_name::*;
pub use crate::role_eligibility_schedules::*;
pub use crate::role_management_policy_assignment_id::*;
pub use crate::role_management_policy_assignment_id_variants::*;
pub use crate::role_management_policy_assignment_name::*;
pub use crate::role_management_policy_assignments::*;
pub use crate::role_management_policy_id::*;
pub use crate::role_management_policy_id_variants::*;
pub use crate::role_operations::*;
pub use crate::role_permission::*;
pub use crate::role_permission_action::*;
pub use crate::role_permission_action_set::*;
pub use crate::route_table::*;
pub use crate::route_table_id::*;
pub use crate::route_table_name::*;
pub use crate::route_table_properties::*;
pub use crate::scope_itertools::*;
pub use crate::scopes::*;
pub use crate::service_group::*;
pub use crate::service_group_id::*;
pub use crate::service_group_name::*;
pub use crate::slug::*;
pub use crate::storage_account::*;
pub use crate::storage_account_blob_container_name::*;
pub use crate::storage_account_id::*;
pub use crate::storage_account_name::*;
pub use crate::subnet::*;
pub use crate::subnet_id::*;
pub use crate::subnet_name::*;
pub use crate::subnet_properties::*;
pub use crate::subscription::*;
pub use crate::subscription_id::*;
pub use crate::subscription_name::*;
pub use crate::tenant_id::*;
pub use crate::tenant_license::*;
pub use crate::test_resource::*;
pub use crate::unified_role_assignment::*;
pub use crate::unified_role_assignment_id::*;
pub use crate::unified_role_definition::*;
pub use crate::unified_role_definition_collection::*;
pub use crate::unified_role_definition_id::*;
pub use crate::unified_role_definitions_and_assignments::*;
pub use crate::user_id::*;
pub use crate::virtual_machine::*;
pub use crate::virtual_machine_id::*;
pub use crate::virtual_machine_name::*;
pub use crate::virtual_machine_properties::*;
pub use crate::virtual_machine_size::*;
pub use crate::virtual_network::*;
pub use crate::virtual_network_id::*;
pub use crate::virtual_network_name::*;
pub use crate::virtual_network_peering_id::*;
pub use crate::virtual_network_peering_name::*;
pub use crate::virtual_network_properties::*;
pub use cloud_terrastodon_azure_resource_types::*;
pub use ipnetwork;
pub use uuid;
