#![feature(pattern, duration_constructors_lite, associated_type_defaults)]
mod accounts;
mod app;
mod container_registry;
mod container_registry_id;
mod container_registry_name;
mod container_registry_repository_name;
mod container_registry_repository_tag;
pub mod cost_management;
mod duration;
mod eligible_child_resources;
mod groups;
mod management_group_ancestors_chain;
mod management_groups;
mod metrics;
mod naming;
mod oauth2_permission_grants;
mod oauth2_permission_scopes;
mod pim_azurerm_role_assignment_schedule_requests;
mod pim_entra_role_assignment_requests;
mod pim_entra_role_assignments;
mod pim_entra_role_definitions;
mod pim_entra_role_settings;
mod policy_assignment_id;
mod policy_assignment_id_variants;
mod policy_assignment_name;
mod policy_assignments;
mod policy_definition_id;
mod policy_definition_id_variants;
mod policy_definition_name;
mod policy_definitions;
mod policy_set_definition_id;
mod policy_set_definition_id_variants;
mod policy_set_definition_name;
mod policy_set_definitions;
mod principals;
mod query_response;
mod resource_group;
mod resource_group_id;
mod resource_group_map;
mod resource_group_name;
mod resource_tags;
mod resources;
mod role_assignment_id;
mod role_assignment_id_variants;
mod role_assignment_name;
mod role_assignments;
mod role_definitions;
mod role_eligibility_schedule_id;
mod role_eligibility_schedule_id_variants;
mod role_eligibility_schedule_name;
mod role_eligibility_schedules;
mod role_management_policy_assignment_id;
mod role_management_policy_assignment_id_variants;
mod role_management_policy_assignment_name;
mod role_management_policy_assignments;
mod role_management_policy_id;
mod role_management_policy_id_variants;
mod scope_itertools;
mod scopes;
mod service_principal;
mod slug;
mod storage_account;
mod storage_account_blob_container_name;
mod storage_account_id;
mod storage_account_name;
mod subnet;
mod subnet_id;
mod subnet_name;
mod subnet_properties;
mod subscription;
mod subscription_id;
mod subscription_name;
mod tenants;
mod test_resource;
mod users;
mod uuid_macros;
mod uuid_wrapper;
mod virtual_network;
mod virtual_network_id;
mod virtual_network_name;
mod virtual_network_properties;
mod uuid_parser_nom;
mod subscription_id_parser_nom;
mod subscription_id_parser_winnow;
mod route_table;
mod route_table_properties;
mod route_table_name;
mod route_table_id;
mod address_prefixes;

pub mod prelude {
    pub use crate::accounts::*;
    pub use crate::address_prefixes::*;
    pub use crate::route_table::*;
    pub use crate::route_table_id::*;
    pub use crate::route_table_name::*;
    pub use crate::route_table_properties::*;
    pub use crate::subscription_id_parser_nom::*;
    pub use crate::subscription_id_parser_winnow::*;
    pub use crate::app::*;
    pub use crate::container_registry::*;
    pub use crate::container_registry_id::*;
    pub use crate::container_registry_name::*;
    pub use crate::container_registry_repository_name::*;
    pub use crate::container_registry_repository_tag::*;
    pub use crate::duration::*;
    pub use crate::eligible_child_resources::*;
    pub use crate::groups::*;
    pub use crate::management_group_ancestors_chain::*;
    pub use crate::management_groups::*;
    pub use crate::metrics::*;
    pub use crate::naming::*;
    pub use crate::oauth2_permission_grants::*;
    pub use crate::oauth2_permission_scopes::*;
    pub use crate::pim_azurerm_role_assignment_schedule_requests::*;
    pub use crate::pim_entra_role_assignment_requests::*;
    pub use crate::pim_entra_role_assignments::*;
    pub use crate::pim_entra_role_definitions::*;
    pub use crate::pim_entra_role_settings::*;
    pub use crate::policy_assignment_id::*;
    pub use crate::policy_assignment_id_variants::*;
    pub use crate::policy_assignment_name::*;
    pub use crate::policy_assignments::*;
    pub use crate::policy_definition_id::*;
    pub use crate::policy_definition_id_variants::*;
    pub use crate::policy_definition_name::*;
    pub use crate::policy_definitions::*;
    pub use crate::policy_set_definition_id::*;
    pub use crate::policy_set_definition_id_variants::*;
    pub use crate::policy_set_definition_name::*;
    pub use crate::policy_set_definitions::*;
    pub use crate::principals::*;
    pub use crate::query_response::*;
    pub use crate::resource_group::*;
    pub use crate::resource_group_id::*;
    pub use crate::resource_group_map::*;
    pub use crate::resource_group_name::*;
    pub use crate::resource_tags::*;
    pub use crate::resources::*;
    pub use crate::role_assignment_id::*;
    pub use crate::role_assignment_id_variants::*;
    pub use crate::role_assignment_name::*;
    pub use crate::role_assignments::*;
    pub use crate::role_definitions::*;
    pub use crate::role_eligibility_schedule_id::*;
    pub use crate::role_eligibility_schedule_id_variants::*;
    pub use crate::role_eligibility_schedule_name::*;
    pub use crate::role_eligibility_schedules::*;
    pub use crate::role_management_policy_assignment_id::*;
    pub use crate::role_management_policy_assignment_id_variants::*;
    pub use crate::role_management_policy_assignment_name::*;
    pub use crate::role_management_policy_assignments::*;
    pub use crate::role_management_policy_id::*;
    pub use crate::role_management_policy_id_variants::*;
    pub use crate::scope_itertools::*;
    pub use crate::scopes::*;
    pub use crate::service_principal::*;
    pub use crate::slug::*;
    pub use crate::storage_account::*;
    pub use crate::storage_account_blob_container_name::*;
    pub use crate::storage_account_id::*;
    pub use crate::storage_account_name::*;
    pub use crate::subnet::*;
    pub use crate::subnet_id::*;
    pub use crate::subnet_name::*;
    pub use crate::subnet_properties::*;
    pub use crate::subscription::*;
    pub use crate::subscription_id::*;
    pub use crate::subscription_name::*;
    pub use crate::tenants::*;
    pub use crate::test_resource::*;
    pub use crate::users::*;
    pub use crate::uuid_wrapper::*;
    pub use crate::virtual_network::*;
    pub use crate::virtual_network_id::*;
    pub use crate::virtual_network_name::*;
    pub use crate::virtual_network_properties::*;
    pub use crate::uuid_parser_nom::*;
    pub use cloud_terrastodon_azure_resource_types::*;
    pub use uuid;
}
