#![feature(async_closure, impl_trait_in_assoc_type, duration_constructors)]
mod auth;
mod eligible_child_resources;
mod evaluate_policy_assignment_compliance;
mod groups;
mod management_groups;
mod name_lookup_helper;
mod pim_azurerm_activate;
mod pim_entra_activate;
mod pim_entra_role_assignments;
mod pim_entra_role_definitions;
mod pim_entra_role_settings;
mod policy_assignments;
mod policy_definitions;
mod policy_set_definitions;
mod query;
mod remediate_policy_assignment;
mod resource_groups;
mod role_assignments;
mod role_definitions;
mod role_eligibility_schedules;
mod role_management_policy_assignments;
mod subscriptions;
mod users;
mod resources;
mod create_role_assignment;
mod storage_accounts;
pub mod prelude {
    pub use crate::auth::*;
    pub use crate::eligible_child_resources::*;
    pub use crate::evaluate_policy_assignment_compliance::*;
    pub use crate::groups::*;
    pub use crate::management_groups::*;
    pub use crate::name_lookup_helper::*;
    pub use crate::pim_azurerm_activate::*;
    pub use crate::pim_entra_activate::*;
    pub use crate::pim_entra_role_assignments::*;
    pub use crate::pim_entra_role_definitions::*;
    pub use crate::pim_entra_role_settings::*;
    pub use crate::policy_assignments::*;
    pub use crate::policy_definitions::*;
    pub use crate::policy_set_definitions::*;
    pub use crate::query::*;
    pub use crate::remediate_policy_assignment::*;
    pub use crate::resource_groups::*;
    pub use crate::role_assignments::*;
    pub use crate::role_definitions::*;
    pub use crate::role_eligibility_schedules::*;
    pub use crate::role_management_policy_assignments::*;
    pub use crate::subscriptions::*;
    pub use crate::users::*;
    pub use crate::resources::*;
    pub use crate::create_role_assignment::*;
    pub use crate::storage_accounts::*;
    pub use azure_types::prelude::*;
}
