[package]
name = "cloud_terrasotodon_core_command"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud_terrasotodon_core_pathing = { workspace = true }
cloud_terrasotodon_core_config = { workspace = true }
tokio = { workspace = true } 
anyhow = { workspace = true } 
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
async-recursion = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
