[package]
name = "cloud_terrastodon_ui_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
crossterm = { workspace = true }
futures = { workspace = true }
eframe = "0.31.1"
