[package]
name = "cloud_terrastodon_ui_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
cloud_terrastodon_core_user_input = { workspace = true }
cloud_terrastodon_core_tofu = { workspace = true }
cloud_terrastodon_core_azure = { workspace = true }
cloud_terrastodon_core_azure_devops = { workspace = true }
cloud_terrastodon_core_command = { workspace = true }
cloud_terrastodon_core_pathing = { workspace = true }
cloud_terrastodon_core_config = { workspace = true }
cloud_terrastodon_core_zombies = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
crossterm = { workspace = true }
futures = { workspace = true }
eframe = { version = "0.31.1", features = ["persistence"] }
egui_extras = { version = "0.31.1", features = ["default", "image"] }
