[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
fzf = { workspace = true }
indicatif = { workspace = true }
tofu = { workspace = true } 
azure = { workspace = true }
command = { workspace = true } 
tracing = { workspace = true }
pathing_types = { workspace = true }
clap = { workspace = true }
