[package]
name = "cloud_terrastodon_core_entrypoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud_terrastodon_core_user_input = { workspace = true }
cloud_terrastodon_core_tofu = { workspace = true } 
cloud_terrastodon_core_azure = { workspace = true }
cloud_terrastodon_core_command = { workspace = true } 
cloud_terrastodon_core_pathing = { workspace = true }
cloud_terrastodon_core_config = { workspace = true }
cloud_terrastodon_ui = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
itertools = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
indicatif = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
humantime = { workspace = true }
opener = { workspace = true }
async-recursion = { workspace = true }
tempfile = { workspace = true }
strum = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
prettyplease = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }