[package]
name = "pathing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
once_cell = { workspace = true }
directories-next = { workspace = true }
