[package]
name = "cloud_terrastodon_visualizer"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["plugins/*"]

[workspace.dependencies]
bevy = "0.14.1"
bevy-inspector-egui = "0.25.2"
bevy_svg = { version = "0.14.0", default-features = false, features = ["2d"] }
camera_plugin = { path = "./plugins/camera" }
leafwing-input-manager = "0.15.0"
azure = { path = "../rust/crates/azure" }
crossbeam-channel = "0.5.13"
tokio = { version = "1.39.2", features = ["full"] }

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy_svg = { workspace = true }
camera_plugin = { workspace = true }
azure = { workspace = true }
